In [6]:
%pip install seaborn

In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print(pd.__version__)
print(sns.__version__)

3.0.2
0.13.2

In [4]:
df = pd.read_csv('tiobe_index_feb_2026.csv')
df

,Rank,Language,Rating_Pct,Change_Pct,Status,Paradigm,Year_Created,Creator,Primary_Use,Typing
0,1,Python,21.81,1.85,↑,Multi-paradigm,1991,Guido van Rossum,"AI/ML, Data Science, Web",Dynamic
1,2,C,11.05,-5.41,↓,Procedural,1972,Dennis Ritchie,"Systems, Embedded, OS",Static
2,3,C++,8.55,-1.72,↓,Multi-paradigm,1985,Bjarne Stroustrup,"Systems, Games, HPC",Static
3,4,Java,8.12,-3.38,↓,Object-oriented,1995,James Gosling,"Enterprise, Android, Web",Static
4,5,C#,6.83,0.73,↑,Object-oriented,2000,Anders Hejlsberg,"Enterprise, Games, Web",Static
5,6,JavaScript,2.92,0.10,↑,Multi-paradigm,1995,Brendan Eich,"Web, Full-stack, Mobile",Dynamic
6,7,Visual Basic,2.85,0.31,↑,Object-oriented,1991,Microsoft,"Enterprise, Desktop",Static
7,8,R,2.19,0.80,↑,Functional,1993,R. Ihaka & R. Gentleman,"Statistics, Data Science",Dynamic
8,9,SQL,1.93,-0.18,↓,Declarative,1974,Donald Chamberlin,"Databases, Analytics",NaN
9,10,Delphi/Object Pascal,1.88,0.42,↑,Object-oriented,1995,Anders Hejlsberg,"Desktop, Enterprise",Static
10,11,Perl,1.67,0.90,↑,Multi-paradigm,1987,Larry Wall,"Text Processing, Scripting",Dynamic
11,12,Fortran,1.55,0.32,↑,Procedural,1957,John Backus,"Scientific, HPC",Static
12,13,PHP,1.48,-0.21,↓,Multi-paradigm,1995,Rasmus Lerdorf,Web Backend,Dynamic
13,14,Rust,1.43,0.38,↑,Multi-paradigm,2010,Graydon Hoare,"Systems, WebAssembly",Static
14,15,Go,1.38,-0.36,↓,Multi-paradigm,2009,Robert Griesemer,"Cloud, Microservices",Static
15,16,MATLAB,1.25,0.17,↑,Multi-paradigm,1984,Cleve Moler,"Engineering, Research",Dynamic
16,17,Scratch,1.18,0.12,↑,Visual,2002,MIT Media Lab,Education,NaN
17,18,Assembly,1.12,-0.22,↓,Imperative,1949,Various,"Embedded, OS Kernels",NaN
18,19,Kotlin,1.08,0.15,↑,Multi-paradigm,2011,JetBrains,"Android, Server-side",Static
19,20,TypeScript,1.05,0.21,↑,Multi-paradigm,2012,Anders Hejlsberg,"Web, Full-stack",Static
20,21,Swift,1.02,-0.08,↓,Multi-paradigm,2014,Apple Inc.,"iOS, macOS",Static
21,22,COBOL,0.76,-0.15,↓,Procedural,1959,Grace Hopper (team),"Banking, Government",Static
22,23,Classic Visual Basic,0.74,-0.05,↓,Object-oriented,1991,Microsoft,Legacy Desktop,Static
23,24,Prolog,0.72,0.10,↑,Logic,1972,Alain Colmerauer,"AI, NLP",Dynamic
24,25,Lua,0.68,0.04,↑,Multi-paradigm,1993,PUC-Rio team,"Games, Embedded",Dynamic
25,26,Ruby,0.65,-0.18,↓,Object-oriented,2005,Yukihiro Matsumoto,"Web, Scripting",Dynamic
26,27,Dart,0.62,0.09,↑,Object-oriented,2011,Google,Mobile (Flutter),Static
27,28,Scala,0.58,-0.06,↓,Multi-paradigm,2004,Martin Odersky,"Big Data, Backend",Static

In [5]:
df.isnull().sum()

Rank            0
Language        0
Rating_Pct      0
Change_Pct      0
Status          0
Paradigm        0
Year_Created    0
Creator         0
Primary_Use     0
Typing          3
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          28 non-null     int64
 1   Language      28 non-null     str
 2   Rating_Pct    28 non-null     float64
 3   Change_Pct    28 non-null     float64
 4   Status        28 non-null     str
 5   Paradigm      28 non-null     str
 6   Year_Created  28 non-null     int64
 7   Creator       28 non-null     str
 8   Primary_Use   28 non-null     str
 9   Typing        25 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 1.6 KB

In [7]:
df = df.fillna('N/A')
df.isnull().sum()

Rank            0
Language        0
Rating_Pct      0
Change_Pct      0
Status          0
Paradigm        0
Year_Created    0
Creator         0
Primary_Use     0
Typing          0
dtype: int64

In [10]:
dg = pd.read_csv('global.csv')
dg

,language,year,creator,first_release,typing_discipline,paradigm,github_repositories,stackoverflow_questions,tiobe_rank,pypl_rank,...,average_salary_usd,learning_difficulty,performance_score,ai_popularity_score,web_development_score,data_science_score,mobile_score,game_dev_score,embedded_score,demand_score
0,Python,2020,Guido van Rossum,1991,Dynamic,"Multi-paradigm (OOP, Functional, Procedural)",191362,148794,1,1,...,113424.84,3.12,45.13,95.88,55.51,96.74,14.93,16.59,13.52,49.56
1,JavaScript,2020,Brendan Eich,1995,Dynamic,"Multi-paradigm (Event-driven, Functional, Prot...",171896,144226,2,2,...,114523.82,3.24,50.87,52.28,94.27,29.18,31.20,53.64,8.36,30.48
2,Java,2020,James Gosling,1995,Static,Object-Oriented,162887,119837,3,3,...,116104.08,4.84,71.33,35.53,61.91,28.86,58.46,28.69,14.75,28.98
3,SQL,2020,Donald D. Chamberlin & Raymond F. Boyce,1974,Static,Declarative,182886,129227,4,4,...,98210.82,2.30,54.69,13.79,33.98,57.58,1.00,1.00,1.00,12.80
4,C++,2020,Bjarne Stroustrup,1985,Static,"Multi-paradigm (OOP, Procedural, Generic)",154821,123211,5,6,...,123501.86,7.63,93.56,21.10,2.67,28.66,2.04,79.02,90.46,18.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Haskell,2026,Simon Peyton Jones et al. (committee),1990,Static,Purely Functional,23686,16368,25,25,...,135389.84,8.09,84.01,2.58,8.07,10.10,5.64,12.43,6.47,15.88
199,Objective-C,2026,Brad Cox & Tom Love,1984,Static,Object-Oriented,23506,14998,26,26,...,121815.03,6.11,71.30,4.49,5.25,1.00,32.19,2.23,11.01,20.35
200,Groovy,2026,James Strachan,2003,Dynamic,"Multi-paradigm (OOP, Functional, Scripting)",18626,13099,27,29,...,125863.75,4.36,62.89,1.97,22.66,1.00,4.35,1.00,1.00,18.50
201,Clojure,2026,Rich Hickey,2007,Dynamic,Functional,14468,11389,28,27,...,139969.42,6.49,69.35,1.00,8.67,7.02,1.00,5.66,1.00,14.87
202,F#,2026,Microsoft (Don Syme),2005,Static,"Functional-first, Multi-paradigm",12849,7970,29,28,...,138443.58,7.10,76.34,1.65,6.22,14.06,10.83,6.57,1.00,16.43

In [12]:
dg['language'].unique()

<StringArray>
[      'Python',   'JavaScript',         'Java',          'SQL',
          'C++',   'TypeScript',           'C#',            'C',
 'Shell (Bash)',          'PHP',           'Go',        'Swift',
         'Ruby',       'Kotlin',            'R',       'MATLAB',
         'Rust',         'Perl',       'VB.NET',        'Scala',
          'Lua',         'Dart',  'Objective-C',       'Groovy',
      'Haskell',       'Elixir',        'Julia',      'Clojure',
           'F#']
Length: 29, dtype: str